server:
  port: ${PORT}

security:
  jwt:
    secret: ${JWT_SECRET}
    user:
      generator: ${JWT_USER_GENERATOR}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

appDescription: "Pragma Powerup"
appVersion: "1.0.0"